"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const kalkulation_class_1 = require("./model/kalkulation.class");
const price_class_1 = require("./model/price.class");
let skistiefel = new kalkulation_class_1.Kalkulation;
skistiefel.listeneinkaufspreis = 205;
skistiefel.listenverkaufspreis = 270;
skistiefel.lieferrabatt = new price_class_1.Price(.12, undefined);
skistiefel.lieferskonto = new price_class_1.Price(.03, undefined);
skistiefel.bezugskosten = 3.20;
skistiefel.handlungskosten = new price_class_1.Price(.18, undefined);
skistiefel.kundenskonto = new price_class_1.Price(.02, undefined);
skistiefel.kundenrabatt = new price_class_1.Price(.10, undefined);
skistiefel.calcGewinn();
skistiefel.print(true);
let fabrik = new kalkulation_class_1.Kalkulation;
fabrik.listeneinkaufspreis = 200 * 8;
fabrik.bezugskosten = 12;
fabrik.listenverkaufspreis = 3.40 * 800;
fabrik.lieferrabatt = new price_class_1.Price(.15, undefined);
fabrik.lieferskonto = new price_class_1.Price(.02, undefined);
fabrik.kundenrabatt = new price_class_1.Price(.30, undefined);
fabrik.kundenskonto = new price_class_1.Price(.03, undefined);
fabrik.handlungskosten = new price_class_1.Price(.20, undefined);
fabrik.calcGewinn();
fabrik.print(true);
